version: '2'
services:

  glpi:
    image: local/glpi
    hostname: glpi
    container_name: glpi
    environment:
      TZ: America/Sao_Paulo
      GLPI_LANG: pt_BR
    volumes:
      - glpi:/var/www/html
    ports:
      - 82:80

  crond:
    image: local/glpi-cron
    hostname: cron
    container_name: cron
    environment:
      TZ: America/Sao_Paulo
    volumes:
      - glpi:/var/www/html

volumes:
  mariadb:
  glpi: