apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-configmap
data:
  MARIADB_DATABASE: glpi
  MARIADB_PASSWORD: glpi-pass
  MARIADB_USER: glpi-user
  MYSQL_ROOT_PASSWORD: vFSWfEwEvpHZG633w
  TZ: America/Sao_Paulo