apiVersion: v1
kind: PersistentVolume
metadata:
  name: glpi-glpi
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    #- ReadWriteMany
    - ReadWriteOnce
  mountOptions:
    - hard
    - nfsvers=4.0
  nfs:
    path: /k3s/glpi/glpi
    server: 192.168.1.2