apiVersion: v1
kind: PersistentVolume
metadata:
  name: glpi-mariadb
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  mountOptions:
    - hard
    - nfsvers=4.0
  nfs:
    path: /k3s/glpi/mariadb
    server: 192.168.1.2