apiVersion: apps/v1
kind: Deployment
metadata:
  name: glpi-app
  labels:
    app: glpi-app
  annotations:
spec:
  selector:
    matchLabels:
      app: glpi-app
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: glpi-app
    spec:
      containers:
      - name: glpi
        image: vcaldo/glpi:glpi-9.5.3
        imagePullPolicy: Always
        # envFrom:
        #   - configMapRef:
        #       name: glpi-configmap
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        volumeMounts:
        - name: glpi-vol
          mountPath: /var/www/html
      - name: cron
        image: vcaldo/glpi:cron-9.5.3
        imagePullPolicy: Always
        # envFrom:
        #   - configMapRef:
        #       name: glpi-configmap
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        volumeMounts:
        - name: glpi-vol
          mountPath: /var/www/html
      volumes:
        - name: glpi-vol
          persistentVolumeClaim:
            claimName: glpi-claim